require:
- rubocop-rspec

Layout/HashAlignment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 40
Metrics/PerceivedComplexity:
  Max: 40
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Max: 150
Naming/VariableNumber:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Lint/RequireParentheses:
  Enabled: false
Lint/RedundantSafeNavigation:
  Enabled: false
Lint/UselessMethodDefinition:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Lint/HeredocIndentation:
  Enabled: false
Lint/EmptyConditionalBody:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false
Lint/SelfAssignment:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Metrics/ParameterLists:
  Max: 6
  MaxOptionalParameters: 4
RSpec:
  Enabled: false
RSpec/Capybara:
  Enabled: false
RSpec/FactoryBot:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'autotest/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
