default: &default
  store_options: &default_store_options
    max_age: <%= 60.days.to_i %>
    namespace: <%= Rails.env %>
  size_estimate_samples: 1000

development:
  database: cache
  store_options:
    <<: *default_store_options
    max_size: <%= 256.megabytes %>

staging:
  database: cache
  store_options:
    <<: *default_store_options
    max_size: <%= 256.megabytes %>

test:
  <<: *default

production:
  database: cache
  store_options:
    <<: *default_store_options
    max_size: <%= 256.megabytes %>
