default: &default
  adapter: postgresql
  encoding: utf8
  template: template0

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE", 'pbm_dev') %>
  host: localhost

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE", 'pbm_test') %>

staging:
  url: <%= ENV["DATABASE_URL"] %>

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV["DOKKU_POSTGRES_BLACK_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV["DOKKU_POSTGRES_QUEUE_URL"] %>
    migrations_paths: db/queue_migrate
