default: &default
  adapter: postgresql
  encoding: utf8
  template: template0

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE", 'pbm_dev') %>
  host: localhost

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE", 'pbm_test') %>

staging:
  primary: &primary_staging
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *primary_staging

production:
  primary: &primary_production
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *primary_production
